name: Deploy to AWS EC2
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Debug Secrets
      run: |
        echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
        echo "EC2_KEY: ${{ secrets.EC2_KEY }}"
    - name: Deploy using SSH
      uses: appleboy/ssh-action@v1.0 частина:3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd cloud-computing-final-project
          git pull
          npm install
          pm2 restart all || pm2 start index.js --name "node-app"
